apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products-ingress
spec:
  tls:
  - hosts:
    - products.proyectodevops.local
    secretName: default-server-secret
  rules:
  - host: products.proyectodevops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: products-service
            port:
              number: 30003
   