apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payments-ingress
spec:
  tls:
  - hosts:
    - payments.proyectodevops.local
    secretName: default-server-secret
  rules:
  - host: payments.proyectodevops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payments-service
            port:
              number: 80
   