apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shipping-ingress
spec:
  tls:
  - hosts:
    - shipping.proyectodevops.local
    secretName: default-server-secret
  rules:
  - host: shipping.proyectodevops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shipping-service
            port:
              number: 30004
   