apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 1
  template:
    metadata:
      name: products-pod
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/products-microservice:49c58a01d4a96b58d5381da1ffe7a6e39a6f0a44
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: products