apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  labels:
    app: payments
spec:
  replicas: 2
  template:
    metadata:
      name: payments-pod
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/payments-microservice:30aec61db5c9c73c6a26b2d768803d9bc0ce6152
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: payments