apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 2
  template:
    metadata:
      name: products-pod
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/products-microservice:a3c1ebfba8af6b8c2338ec8810f6ed97d58a3796
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: products