apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
  labels:
    app: orders
spec:
  replicas: 2
  template:
    metadata:
      name: orders-pod
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/orders-microservice:0ec74623394930eade75c2833822d0c0198ffc8f
          env:
            - name: paymentsUrl
              value: http://$(PAYMENTS_SERVICE_SERVICE_HOST)
            - name: shippingUrl
              value: http://$(SHIPPING_SERVICE_SERVICE_HOST)
            - name: productsUrl
              value: http://$(PRODUCTS_SERVICE_SERVICE_HOST)

          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: orders