apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  labels:
    app: payments
spec:
  replicas: 2
  template:
    metadata:
      name: payments-pod
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/payments-microservice:8e25aa4b7f23b8db8dda5dca096fa789b42cd5cf
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: payments