apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  labels:
    app: payments
spec:
  replicas: 2
  template:
    metadata:
      name: payments-pod
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/payments-microservice:6d3fc96b42aefd2032ec03847789cf45245f41d8
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: payments