apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 2
  template:
    metadata:
      name: products-pod
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/products-microservice:d33f8ca67db5ddf7e03d5246953b328aff83a3c2
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: products