apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 2
  template:
    metadata:
      name: products-pod
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/products-microservice:9c6381bb345647f9ea04966f7bfd7848117a02f2
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: products