apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  labels:
    app: products
spec:
  replicas: 2
  template:
    metadata:
      name: products-pod
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: southamerica-east1-docker.pkg.dev/proyectodevopsort/proyecto-devops-ort/products-microservice:3e9a02e2e4a78e63de1a6ca67dd328f208489375
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: products