name: Reusable workflow example

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-folder:
        required: true
        type: string
    secrets:
      sonar-token:
        required: true

jobs:

  build_orders:
  
    name: Build $inputs.service-name Service
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Infra
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build $inputs.service-name Service
        working-directory: /home/runner/work/$inputs.service-folder
        run: mvn --batch-mode --update-snapshots package       