name: Reusable workflow example

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      service-folder:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true


jobs:

  build_orders:
  
    name: format('Build {0} Service', $inputs.service-name)  
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Infra
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: format('Build {0} Service', $inputs.service-name)  
        working-directory: format('/home/runner/work/{0}', $inputs.service-folder)
        run: mvn --batch-mode --update-snapshots package       